vault_path: /home/rudyon/memx
output_path: /home/rudyon/Developmentrudyon.github.io
pages:
  - plan9.md
  - conformity.md
  - shivi.md
  - ultralearning.md
  - 'guns germs and steel.md'
  - sapiens.md
